### ISSUE TITLE
Clicking submit on a sponsorship reply publishes the post but opens a post editor with random text

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#583] opened 2023-12-20 17:11 UTC
**Current Behavior:**
https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/8cb7405e-a6ca-4c6f-aab3-30751e5b98d4

**Desired Behavior:**
After submitting the sponsorship reply, I should only see that and not the editor window.

**Comment by PiVortex** [comment] 2023-12-21 13:45
I can confirm the same issue. 

When making a comment on a post, it will open the markdown editor filled in with the post that I was replying to. 
I also cannot close this window.

**Comment by Megha-Dev-19** [comment] 2023-12-21 15:01
this is weird, I'll check

**Comment by Megha-Dev-19** [comment] 2023-12-21 15:51
hey @ori-near, I debugged the issue, it happens because we store the state in local storage after submit is clicked, if I remove that it works fine.
@ailisp, can you please tell me why did we add this?

**Comment by ailisp** [comment] 2023-12-22 02:42
a good answer from @frol  to this question:
>  @ailisp, can you please tell me why did we add this?

If user gets redirected to their wallet, the page is gone and so if transaction does not succeed on the wallet side, users lose their whole post and won't be able to post it later

**Closed** 2023-12-22 05:46 UTC
Labels: bug

**Comment by ori-near** [comment] 2023-12-22 20:02
Thank you for fixing this!
