### ISSUE TITLE
feat: Display cumulative comments count

### ISSUE THREAD

**Issue by nearmax** [NEAR-DevHub/neardevhub-bos#11] opened 2023-02-13 16:56 UTC
Currently we are showing the number of comments under each post. However, this is the number of immediate comments, and if there nested level 2+ comments they won't be included in this counter. However, it makes more sense to show cumulative count of all comments in the comments tree for each post. We can either calculate this number directly in UI or include counter into the smart contract logic.

### Example

https://near.org/#/devgovgigs.near/widget/gigs-board.pages.Post?id=711

### Current behaviour

It shows that there are only 3 comments

### Expected behaviour

It should display 5 (3 immediate comments + 2 nested)

### Suggested implementation

1. Introduce a new function `get_posts_recursively` next to [`get_post` function on DevHub smart contract](https://github.com/near/neardevhub-contract/blob/main/src/lib.rs#L83-L86), so we don't need to fetch all the nested posts from UI one by one crashing the API server
2. Use that new function from DevHub components, and thus count the cumulative comments on the UI properly.

### Tips

Here is the starting point on the UI side:

https://github.com/near/neardevhub-widgets/blob/b9c26222f672d605f2f171a8d50ff21a124bcab3/src/gigs-board/pages/Post.jsx#L55-L59

**Comment by Dhruv245** [comment] 2023-06-21 18:29
Hi, Would love to try it.

**Comment by Rishabhraghwendra18** [comment] 2023-11-01 17:39
Hi @carina-akaia are you still working on this issue?

**Comment by carina-akaia** [comment] 2023-11-01 22:08
@Rishabhraghwendra18 hi, it's still in the backlog and I didn't start working on it yet. I can reassign it to you if you want to tackle this

**Comment by Rishabhraghwendra18** [comment] 2023-11-02 05:10
@carina-akaia please assign it to me

**Comment by carina-akaia** [comment] 2023-11-02 12:37
> @carina-akaia please assign it to me

@Rishabhraghwendra18 done!

**Comment by Rishabhraghwendra18** [comment] 2023-11-06 14:01
@carina-akaia I need some help to set up `neardev-contract` repo. I have opened a decision regarding this: https://github.com/near/neardevhub-widgets/discussions/447

Thanks

**Comment by ori-near** [comment] 2023-11-15 00:58
Hi @Rishabhraghwendra18 – how is this ticket going? Are you still blocked?

**Comment by Rishabhraghwendra18** [comment] 2023-11-15 08:39
Hello @ori-near, I am busy with my full-time job for next 2 weeks. Anyone can take it up, otherwise I will get back on this after 2 weeks. 

Really sorry for inconvenience.

**Comment by ori-near** [comment] 2023-11-28 19:15
Hi @Rishabhraghwendra18 – hope all is well. I am putting this ticket back in the backlog. Let us know if you'd still like to pick this up. Otherwise, anyone else can grab it. Thanks.

**Comment by Tguntenaar** [comment] 2023-12-18 11:23
The example nearmax mentioned is outdated so here is the new one: [https://near.org/devhub.near/widget/app?page=post&id=711](https://near.org/devhub.near/widget/app?page=post&id=711)

**Comment by Tguntenaar** [comment] 2024-01-05 15:23
Will close this issue, since proposals and announcements will fix many of the issues by design or will require rethinking of the approach

**Closed by Tguntenaar** 2024-01-05 15:23 UTC
Labels: enhancement
